リザルト画面調整
ktakahiro150397/RankPrediction_Web pull request #112
Opened 2021-09-09 10:10 UTC by WagashiMgmg

急にアフィ臭くなって共有してもらえない気がしてレイアウト前後させようと思った。
共有文句でいきなり感謝されると怖い。詐欺サイト感ある気せん？

2021-09-09 10:12 UTC, WagashiMgmg commented
![image](https://user-images.githubusercontent.com/42840776/132667691-f640c0a1-55d8-48c5-8f31-bff8fdf33c08.png)
ちょっと寂しいか

2021-09-09 10:17 UTC, ktakahiro150397 commented
まあ唐突すぎる感じは確かにある

2021-09-09 10:29 UTC, WagashiMgmg commented
共有ボタンとアフィゾーンの入れ替えは必須にみえた。その順番で入れたの自分やけど

2021-09-09 15:46 UTC, WagashiMgmg commented on RankPrediction_Web/Views/ApexRank/Result.cshtml
> +                    <a>
じゃあpやな

2021-09-09 15:56 UTC, WagashiMgmg commented
a タグからp タグにした。共有文句もちょい変えた

2021-09-09 16:00 UTC, WagashiMgmg commented on RankPrediction_Web/Views/ApexRank/Result.cshtml
> +            診断結果を共有してみませんか？<br />
唐突の感謝から唐突の労いへ

2021-09-10 10:06 UTC, WagashiMgmg commented on RankPrediction_Web/Views/ApexRank/Result.cshtml
> +            診断結果を共有してみませんか？<br />
感謝・労いはやはり胡散臭い

2021-09-10 10:08 UTC, WagashiMgmg commented
![image](https://user-images.githubusercontent.com/42840776/132837767-d24b8512-731e-40b2-82fa-e7fe598e436c.png)
![image](https://user-images.githubusercontent.com/42840776/132837833-7fd1aef8-62f5-4801-b2a5-e2a4e1e45224.png)

2021-09-10 10:12 UTC, ktakahiro150397 commented
マージ対象は一旦developに変更

2021-09-10 10:13 UTC, ktakahiro150397 commented on RankPrediction_Web/Views/ApexRank/Result.cshtml
> +            ユーザーが増えていくと、AIは進化していきます。しばらく時間を置いて、また訪ねてみてください。<br />
これめっちゃいい

2021-09-10 10:15 UTC, ktakahiro150397 requested changes
「想像どおりの結果でしたか？」っていうsectionと、「共有してみませんか」のsectionの2つに分けるべきかも

2021-09-10 10:18 UTC, WagashiMgmg commented
https://github.com/ktakahiro150397/RankPrediction_Web/pull/112#pullrequestreview-751262089
やってみる

2021-09-10 10:20 UTC, WagashiMgmg commented
![image](https://user-images.githubusercontent.com/42840776/132839344-10ff14fb-57a4-4866-a499-072b96229d33.png)
![image](https://user-images.githubusercontent.com/42840776/132839373-bac7b76c-bbf9-4410-a5a3-fbed5c2be23a.png)
良い感じや

2021-09-10 10:23 UTC, ktakahiro150397 reviewed
いいね

2021-09-10 10:23 UTC, ktakahiro150397 approved these changes

2021-09-10 10:24 UTC, ktakahiro150397 commented
満足いけばマージしちゃってください！

2021-09-10 10:34 UTC, merged

2021-09-10 10:34 UTC, WagashiMgmg commented
うし