Wagashi/result
ktakahiro150397/RankPrediction_Web pull request #130
Opened 2021-09-17 11:29 UTC by WagashiMgmg

2021-09-18 01:23 UTC, ktakahiro150397 requested changes
対応付けの部分も修正おなしゃす

2021-09-18 01:23 UTC, ktakahiro150397 commented on RankPrediction_Web/Models/PredictionResult.cs
> +                        .Where(item => item.RankGeneralId == (PredictResult.RankId / 4) + 1)// /4+1でrankidとamazon rank_general_idを対応づけ
ここの対応は[rank_relation]テーブルをJOINメソッドで結合して取得するように修正してください
DbContextはDevelopにプッシュしてるのでそっちからマージ頼みます

2021-09-18 01:28 UTC, ktakahiro150397 commented on RankPrediction_Web/Models/PredictionResult.cs
> +                        .Where(item => item.RankGeneralId == (PredictResult.RankId / 4) + 1)// /4+1でrankidとamazon rank_general_idを対応づけ
https://github.com/ktakahiro150397/RankPrediction_Web/blob/382691a58fdcf093560a0744b382f893d612af01/RankPrediction_Web/Models/PredictionResult.cs#L83-L95

ここ参考で
第一引数に結合対象、第二引数・第三引数に結合条件、第四引数に返却するオブジェクトを指定する感じ

2021-11-12 13:43 UTC, WagashiMgmg commented
一応表示されるようになった。コードが正しいか見てほしです。

2021-11-12 16:56 UTC, ktakahiro150397 commented
こーど○

2021-11-12 16:57 UTC, ktakahiro150397 approved these changes

2021-11-12 16:58 UTC, merged